//
// Module uart_v2k.address_decode.tbl
//
// Created:
//          by - user.group (host.domain)
//          at - 12:00:43 17/05/2007
//
// Generated by Mentor Graphics' HDL Designer(TM) 2007.1
//

`resetall
`timescale 1ns/10ps
module address_decode( 
   // Port Declarations
   input   wire    [2:0]  addr, 
   input   wire           clk, 
   output  reg            clk_div_en, 
   output  reg            clr_int_en, 
   input   wire           rst, 
   output  reg     [1:0]  ser_if_select, 
   output  reg            xmitdt_en
);


// Internal Declarations



// Local declarations
 

/////////////////////////////////////////////////////////////////
always @ * begin : truth_table_block_proc

   // Global Actions
   clk_div_en = 0;
   xmitdt_en = 0;
   clr_int_en = 0;
   ser_if_select = 2'b0;


   // Block 1
   case (addr)
      0 :
         clk_div_en = 1;
      1 :
         clk_div_en = 1;
      4 :
         begin
            xmitdt_en = 1;
            ser_if_select = addr[1:0];
         end
      5 :
         ser_if_select = addr[1:0];
      6 :
         ser_if_select = addr[1:0];
      7 :
         clr_int_en = 1;
      default:
         begin
            clk_div_en = 0;
            xmitdt_en = 0;
            ser_if_select = "11";
            clr_int_en = 0;
         end
   endcase
end

endmodule // address_decode

