//
// Module uart_v2k.uart_tb.struct
//
// Created:
//          by - user.group (host.domain)
//          at - 12:00:44 17/05/2007
//
// Generated by Mentor Graphics' HDL Designer(TM) 2007.1
//

`resetall
`timescale 1ns/10ps
module uart_tb;


// Internal Declarations


// Local declarations

// Internal signal declarations
wire  [2:0] addr;              // 3-bit address bus
wire  [7:0] buffered_datout;
wire        clk;               // 10 MHz clock
wire        cs;                // chip select
wire  [7:0] datin;             // 8-bit data in bus from cpu
wire  [7:0] datout;            // 8-bit data out bus to cpu
wire        int;               // interrupt(1)
wire        nrw;               // read(0), write(1)
wire        rst;               // reset(0)
wire        sin;               // serial input
wire        sout;              // serial output


// Instances 
tester #(100) U_0( 
   .buffered_datout (buffered_datout), 
   .datout          (datout), 
   .int             (int), 
   .sout            (sout), 
   .addr            (addr), 
   .clk             (clk), 
   .cs              (cs), 
   .datin           (datin), 
   .nrw             (nrw), 
   .rst             (rst), 
   .sin             (sin)
); 

uart_top U_1( 
   .addr            (addr), 
   .clk             (clk), 
   .cs              (cs), 
   .datin           (datin), 
   .nrw             (nrw), 
   .rst             (rst), 
   .sin             (sin), 
   .buffered_datout (buffered_datout), 
   .datout          (datout), 
   .int             (int), 
   .sout            (sout)
); 


endmodule // uart_tb

